name = "strengths-profile-jp"
type = "javascript"
compatibility_date = "2024-01-01"
preview_urls = false

[build]
command = ""
watch_paths = []
cwd = "."
build_watch_paths = []

[env.production]
route = ""
zone_id = ""

[build.upload]
format = "service-worker"

[[rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.json", "**/*.md"]
fallthrough = true

[site]
bucket = "."
include = ["*.html"]
exclude = []
